## ----------------------------------------------------------------------------

title : AwsSum
tagline: Node.js modules for talking to lots of Web Service APIs.
author :
  name : Andrew Chilton
  email : chilts@appsattic.com
  github : chilts
  twitter : andychilton

version : v0.12.2

url : http://awssum.io
assets : /s

## ----------------------------------------------------------------------------
